version: "3.3"
services:
  ssl:
    build: ssl
    volumes:
      - sslcerts:/var/ssl/keys
  nginx:
    image: "nginx:1.21"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - sslcerts:/root/certs
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    networks:
      - laravelnet
  phpmyadmin:
    image: "nginx:1.21"
    volumes:
      - ./phpmyadmin/client:/var/www/phpmyadmin
      - ./nginx/phpmyadmin.conf:/etc/nginx/conf.d/default.conf
      - sslcerts:/root/certs
    ports:
      - "7600:7600"
    networks:
      - laravelnet
  php:
    build: php
    ports:
      - "9090:9090"
    volumes:
      - ./app:/var/www/html
      - ./phpmyadmin/client:/var/www/phpmyadmin
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravelnet
  mysql:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - laravelmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - laravelnet
networks:
  laravelnet:
volumes:
  laravelmysql:
  sslcerts:
